### ISSUE TITLE
[Bug]: Connect to Workspace block is shown even after the user has connected to the workspace

### ISSUE THREAD

**Issue by brf153** [RocketChat/Apps.Notion#33]
### What happened?

We should not allow multiple connections to the same workspace. We should notify the user that he/she is already connected to the workspace they are trying to connect to.

### Steps to reproduce

1. Try to connect to a workspace.
2. After connecting, try again to connect to the workspace.
3. You will be notified again that you have been connected.

### Relevant ScreenShots

![Screenshot from 2024-01-15 12-25-35](https://github.com/RocketChat/Apps.Notion/assets/107868772/188b90a5-e00d-4718-a814-02d1438a5eb5)

### Version

v6.5.2

### What browsers are you seeing the problem on?

Chrome

**Comment by brf153** [comment]
@Nabhag8848 shall I work on the issue? I have actually made the changes and I just wanted to know whether it is the right approach or not. After connecting the user to the workspace, we store the user's info in the oauthstorage persistance. Now, I will check whether the data with user's id is present or not in the persistance. If it is present then I will make a template which states that you are already connected to the workspace.

**Comment by brf153** [comment]
https://github.com/RocketChat/Apps.Notion/assets/107868772/11952e4b-f3fd-4046-8293-32c71e724404

**Comment by Nabhag8848** [comment]
> @Nabhag8848 shall I work on the issue? I have actually made the changes and I just wanted to know whether it is the right approach or not. After connecting the user to the workspace, we store the user's info in the oauthstorage persistance. Now, I will check whether the data with user's id is present or not in the persistance. If it is present then I will make a template which states that you are already connected to the workspace.

Hey, the technical approach is correct but overall this isn't what we need cause it can make to lot of issues also note when we are connecting again to same workspace the tokenInfo (accessToken with notion workspace info) is being override

Some reasons why not: 
- the reconnection could be due to many reasons:  user has changed the workspace info or maybe admin had make changes to the permissions and that could require reconnecting to workspace or maybe notion would introduce refreshToken in their auth flow.

Some more tip: 
- Its great practice to avoid making pr's before confirmation from maintainers of orgs.

**Comment by brf153** [comment]
@Nabhag8848 oki bhaiya. Thank you for reviewing the issue. Also, can you suggest me some issues on which I could work?
